version: 1.0
name: Empires
main: com.empires.core.Main
author: Samuel Dauchert
description: Testing that Plugin!
commands:
  config:
    aliases: [con]
    description: Display configuration parameters!
  heal:
    aliases: [h]
    description: Heals a player.
  number:
    description: Pick a number, any number!
  spawnNPC:
    description: Spamn an NPC at player's current position.
